version: '3.7'

volumes:
  pg_bot_data:
  redis_data:

services:
  db:
    container_name: db_container
    image: postgres:16.1
    env_file: .env
    restart: always
    volumes:
      - pg_bot_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3
  
  redis:
    container_name: redis_container
    image: redis:6.0
    env_file: .env
    restart: always
    volumes:
      - redis_data:/var/redis_data
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${PASSWORD_REDIS}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${PASSWORD_REDIS}", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
  
  bot:
    container_name: bot_container
    build: ./bot/
    env_file: .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

